version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ecom_postgres
    environment:
      POSTGRES_DB: ecomdb
      POSTGRES_USER: ecomuser
      POSTGRES_PASSWORD: ecompass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecom_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    image: ecom-app-img:v2
    container_name: ecom_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecomdb
      SPRING_DATASOURCE_USERNAME: ecomuser
      SPRING_DATASOURCE_PASSWORD: ecompass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata:
